
export {default as Home} from './Home.jsx'
export {default as NotFound} from './NotFound.jsx'
export {default as PitchDecks} from './PitchDecks.jsx'
export {default as GlobalStartups} from './GlobalStartups.jsx'
export {default as Ideas} from './Ideas.jsx'
export {default as CaseStudies} from './CaseStudies.jsx'
export {default as CaseStudyDetail} from './CaseStudyDetail.jsx'
export {default as CountryStartups} from './CountryStartups.jsx'
export {default as BangladeshStartups} from './BangladeshStartups.jsx'
export {default as VCInfo} from './VCInfo.jsx'
export {default as LeadingStartups} from './LeadingStartups.jsx'
export {default as Big} from './Big.jsx'
